spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.153.122/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.30.113
    port: 6379
    password: 123456

server:
  context-path: /sell

wechat:
  mpAppId: appId
  mpAppSecret: appSecret
  openAppId: openAppId
  openAppSecret: openAppSecret
  mchId: mchId
  mchKey: mchKey
  keyPath: keyPath/h5.p12
  notifyUrl: http://sell.natapp4.cc/selll/pay/notify
  templateId:
    orderStatus: orderStatus

projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc

logging:
  level:
    com.gittoy.dataobject.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
